# Generated by Django 4.2.2 on 2023-07-29 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=60, null=True)),
                ('player_word', models.CharField(blank=True, max_length=60, null=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('used_letters', models.CharField(blank=True, max_length=30, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
