# Generated by Django 4.2.2 on 2023-08-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0002_userwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordhistory',
            name='hard',
            field=models.BooleanField(default=False),
        ),
    ]
