# Generated by Django 4.2.2 on 2023-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0003_userwordhistory_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordhistory',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
