# Generated by Django 4.2.2 on 2023-08-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0005_remove_userwordhistory_hard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordhistory',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
