# Generated by Django 4.2.2 on 2023-08-16 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0006_userwordhistory_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_ratio', models.PositiveSmallIntegerField(default=0)),
                ('win_efficiency', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
