# Generated by Django 4.2.2 on 2023-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0007_userscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorecard',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
