# Generated by Django 4.2.2 on 2023-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0010_alter_guestbook_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestbook',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userscorecard',
            name='win_ratio',
        ),
        migrations.AddField(
            model_name='userscorecard',
            name='won_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
