# Generated by Django 4.2.2 on 2023-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0012_delete_guestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorecard',
            name='win_ratio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
