# Generated by Django 4.2.2 on 2023-08-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0013_userscorecard_win_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscorecard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_by_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
