# Generated by Django 4.2.2 on 2023-08-20 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0014_alter_userscorecard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordhistory',
            name='date_done',
            field=models.DateField(default=datetime.date(2023, 8, 19)),
        ),
    ]
